# Generated by Django 5.0.3 on 2024-06-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_video_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadmodel',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='threadmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='thread',
        ),
        migrations.DeleteModel(
            name='MessageModel',
        ),
        migrations.DeleteModel(
            name='ThreadModel',
        ),
    ]
