# Generated by Django 5.0.6 on 2024-06-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0017_remove_threadmodel_receiver_remove_threadmodel_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cover_photo",
            field=models.ImageField(
                blank=True,
                default="uploads/profile_photos/default_cover.png",
                upload_to="uploads/cover_photos",
            ),
        ),
    ]
