# Generated by Django 5.0.3 on 2024-06-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_userprofile_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='uploads/cover_photos/default_cover.png', upload_to='uploads/cover_photos'),
        ),
    ]
